ARG jekyll_version=3.8
FROM jekyll/jekyll:${jekyll_version}

MAINTAINER Ente "ducksource@duckpond.ch"

RUN set -ex \
  && echo 'http://dl-cdn.alpinelinux.org/alpine/v3.5/main' >> /etc/apk/repositories
